name: Test Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request:
  push:
    branches:
      - fixed
jobs:
  test_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: astral-sh/setup-uv@v5
      - uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: nlm-sut
      - name: Run tests
        run: |
          docker run -d -p 5010:5001 nlm-sut 
          sleep 20
          uv sync --only-dev && uv run pytest test_api.py
