name: Lint

on:
  pull_request:
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "poetry.lock"
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: latest

      - run: |
          uvx black[jupyter] --check .
          uvx isort --check .
